name: Gitleaks Scan

on:
  push:
    branches:
      - main  # or the branch you want to monitor
  pull_request:
    branches:
      - main  # or the branch you want to monitor

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Gitleaks
      uses: zricethezav/gitleaks-action@v2.1.0
      with:
        gitleaks_version: v8.0.0  # optional: specify a version of gitleaks
        scan: true
        scan_paths: "src/*,!src/internal/infrastructure/db/migrations/*"
        config: .gitleaks.toml  # optional: specify custom config file
        redacted: true  # optional: redacts secrets in the output (useful in public repos)
