name: GitLeaks Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run GitLeaks
        uses: zricethezav/gitleaks-action@v2.1.0
        with:
          config: ""
          verbose: true
          redacted: false

      - name: Upload GitLeaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks.json
